export const imagesActionType = {
  SET_TAB: 'SET_TAB',
  FETCH_IMAGES_PENDING: 'FETCH_IMAGES_PENDING',
  FETCH_IMAGES_SUCCESS: 'FETCH_IMAGES_SUCCESS',
  FETCH_IMAGES_ERROR: 'FETCH_IMAGES_ERROR',
  NEXT_IMAGE: 'NEXT_IMAGE',
  PREVIOUS_IMAGE: 'PREVIOUS_IMAGE',
  IMAGE_ON_LOAD: 'IMAGE_ON_LOAD',
};
